config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  root "users#index"
  resources :hanks
  resources :toms
  resources :jacks
  resources :taskhanks


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hank.rb
class Hank < ApplicationRecord
  mount_uploader :file_location, PhotoImageUploader  
  validates_presence_of :name, :date, :note, :file_location  
end

app/models/jack.rb
class Jack < ApplicationRecord
end

app/models/taskhank.rb
class Taskhank < ApplicationRecord

end

app/models/tom.rb
class Tom < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hanks_controller.rb
class HanksController < ApplicationController
  before_action :find_data , :only => [:destroy, :show, :edit, :update]
  def index
    @hanks=Hank.all
  end

  def destroy
 
  @hank.destroy

  redirect_to hanks_url
  end

  def new
    @hank=Hank.new
  end

  def create
    @hank=Hank.new(get_params)
    if @hank.save
      redirect_to hanks_url
    else
      render action: :new
    end
  end



  def update
 
    if @hank.update_attributes(get_params)
    redirect_to hanks_url
  else
    render action: :edit
  end
  end



private
def get_params
  params.require(:hank).permit(:name, :date, :note, :file_location)

end
def find_data
  @hank=Hank.find(params[:id])
end


end

app/controllers/jacks_controller.rb
class JacksController < ApplicationController
   def index
  end
end

app/controllers/taskhanks_controller.rb
class TaskhanksController < ApplicationController
  before_action :get_task, :only => [:update, :destroy]

  def index
    @tasks=Taskhank.all
    @today=Date.today
  end

  def update
     @task.update_attributes(get_params)

     redirect_to taskhanks_path
   end

   def new
    @task=Taskhank.new
   end

   def create
    @task=Taskhank.new(get_params)
    if @task.save
    redirect_to taskhanks_path
    else
      render :action => :new
    end
   end

   def destroy
    @task.delete
    redirect_to taskhanks_path
   end

   private
   def get_params
     params.require(:taskhank).permit(:task, :due_date, :note, :status)
   end

   def get_task
     @task = Taskhank.find(params[:id])
   end

end

app/controllers/toms_controller.rb
class TomsController < ApplicationController
   def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @user=User.new

  end

  def create
    @user=User.new(get_params)
   
    temp1=User.find(1)
    temp2=User.find(2)
    temp3=User.find(3)

    if temp1.name == @user.name && temp1.password == @user.password
    redirect_to taskhanks_url
    elsif temp2.name == @user.name && temp2.password == @user.password
    redirect_to toms_url
    elsif temp3.name == @user.name && temp3.password == @user.password
    redirect_to jacks_url
    else  
      redirect_to users_url
    end

  end


  private

  def get_params
    params.require(:user).permit(:name, :password)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hanks_helper.rb
module HanksHelper
end

app/helpers/jacks_helper.rb
module JacksHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/taskhanks_helper.rb
module TaskhanksHelper
end

app/helpers/todohanks_helper.rb
module TodohanksHelper
end

app/helpers/toms_helper.rb
module TomsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hanks/_form.html.erb
<div class="form container">
  <%= form_for @hank do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :date %>
      <%= f.text_field :date, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :note %>
      <%= f.text_field :note, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :file_location %>
      <%= f.file_field :file_location %>
    </div>
    <%= f.submit (@hank.persisted? ? "Update" : "Create") %>
  <% end %>

<% if @hank.errors.present? %>
<% @hank.errors.each do |err,mess| %>
<h1 class="text-danger"><span class="glyphicon glyphicon-remove-sign text-danger"></span><%= "#{err} #{mess}" %></h1>
<% end %>
<% end %>
</div>
</div>

app/views/hanks/edit.html.erb
<%= render :partial => "form" %>

app/views/hanks/index.html.erb
<div class="navbar navbar-default navbar-fixed-top navbar-info">
  <div class="container">
    <div class="navbar-header">  
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#qqq">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Hank's photo", hanks_path,class: "navbar-brand" %>
      
    </div>
    <div class="collapse navbar-collapse" id="qqq">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "photo", hanks_path %></li>
        <li><%= link_to "To do list", taskhanks_path %></li>

      </ul>
      <%= link_to "", new_hank_path ,class: "btn btn-primary glyphicon glyphicon-open navbar-right navbar-btn"%>
    </div>
    
    </div>
  </div>
  <br />
  <br />
  <hr />

<div class="container">
  <% @hanks.each do |photo| %>

  <div class="thumbnail col-md-3 col-sm-4 col-xs-10" >

    <%= image_tag photo.file_location.url %>   <!--why ???-->

    <div class="caption">
    <ul class="list-group well">
    <li class="list-group-item list-group-item-danger"><%= photo.name %></li>
    <li class="list-group-item list-group-item-info"><%= photo.date %></li>
    <li class="list-group-item list-group-item-success"><%= photo.note %></li>
    <br>
  
    </ul>
    <div class="button-group text-center">
      <%= link_to "大圖", hank_path(photo), class: "btn btn-primary btn-xs" %>
      <%= link_to "編輯", edit_hank_path(photo), class: "btn btn-primary btn-xs" %>
      <%= link_to "刪除", hank_path(photo), class: "btn btn-primary btn-xs", method: :delete, data:{ confirm: "Are you sure?" } %>
    </div>
  </div>
</div>
  <% end %>



  

app/views/hanks/new.html.erb
<%= render :partial => "form" %>

app/views/hanks/show.html.erb
<style>

.container {
  max-width: 50%;
  margin: 30px auto;
}

.my-set {
  width: 100%;
}

</style>

<div class="container">

<%= image_tag @hank.file_location.url, class: "my-set" %> 
</div>
<%= link_to "返回", hanks_path, class: "btn btn-primary col-xs-offset-6" %>

app/views/jacks/index.html.erb
<h1>hello! Jack</h1>

app/views/taskhanks/index.html.erb
<style>

h3 {
  display: inline-block;
}
.button-group {
  display: inline-block;
  float: right;
}

</style>

<div class="navbar navbar-default navbar-fixed-top navbar-info">
  <div class="container">
    <div class="navbar-header">  
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#qqq">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Hank's Task", hanks_path,class: "navbar-brand" %>
      
    </div>
    <div class="collapse navbar-collapse" id="qqq">
      <ul class="nav navbar-nav">
        <li><%= link_to "photo", hanks_path %></li>
        <li class="active"><%= link_to "To do list", taskhanks_path %></li>

      </ul>
      <%= link_to "", new_taskhank_path ,class: "btn btn-primary glyphicon glyphicon-open navbar-right navbar-btn" %>
    </div>
    
    </div>
  </div>
  <br />
  <br />
  <hr />

<div class="container col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2">
<h3>待處理</h3>
<% @tasks.each do |task| %>

<% if (task.due_date-@today).to_i >=0 && task.status != true %>


<div class="panel-group" id="accordion">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">

<%= form_for task, :url => taskhanks_path,:url => taskhank_path(task) do |f| %>

<%= f.check_box :status, {}, "true", "false" %>
<%= f.label task.task %>
</h3>
<div class="button-group text-right">
<a href=<%= "#"+task.id.to_s %> class="btn btn-primary btn-xs" data-toggle="collapse" data-parent="accordion">detail</a>
<%= f.submit "Submit",class: "btn btn-primary btn-xs" %>
<%= link_to "Delete", taskhank_path(task),class: "btn btn-primary btn-xs", method: :delete, data:{confirm: "確定刪除嗎?"} %>
</div>
</div>
<div id=<%= task.id %> class="panel-collapse collapse out">
<div class="row">
<div class="col-xs-5 col-xs-offset-1"><h5><strong><%= "Due day" %>
<%= task.due_date %></strong></h5></div>
<div class="col-xs-5 col-xs-offset-1"><%= f.label :note %>
<%= f.text_field :note%></div>
</div>
</div>

</div></div>

<% end %>


<% end %>

<% end %>

</div>

<!--上面是未完成 沒過期panel -->
<br />
<div class="container col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2">
<h3>過期</h3>

<% @tasks.each do |task| %>

<% if (task.due_date-@today).to_i < 0 && task.status != true %>


<div class="panel-group" id="accordion">
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title">

<%= form_for task, :url => taskhanks_path,:url => taskhank_path(task) do |f| %>

<%= f.check_box :status, {}, "true", "false" %>
<%= f.label task.task %>
</h3>
<div class="button-group text-right">
<a href=<%= "#"+task.id.to_s %> class="btn btn-primary btn-xs" data-toggle="collapse" data-parent="accordion">detail</a>
<%= f.submit "Submit",class: "btn btn-primary btn-xs" %>

</div>
</div>
<div id=<%= task.id %> class="panel-collapse collapse out">
<div class="row">
<div class="col-xs-5 col-xs-offset-1"><h5><strong><%= "Due day"%>
<%= task.due_date %></strong></h5></div>
<div class="col-xs-5 col-xs-offset-1"><%= f.label :note %>
<%= f.text_field :note%></div>
</div>
</div>

</div></div>

<% end %>


<% end %>

<% end %>
</div>

<!--已完成 -->
<br />
<div class="container col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2">
<h3>完成</h3>

<% @tasks.each do |task| %>

<% if task.status == true %>


<div class="panel-group" id="accordion">
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title">

<%= form_for task, :url => taskhanks_path,:url => taskhank_path(task) do |f| %>

<%= f.check_box :status, {}, "true", "false" %>
<%= f.label task.task %>
</h3>
<div class="button-group text-right">
<a href=<%= "#"+task.id.to_s %> class="btn btn-primary btn-xs" data-toggle="collapse" data-parent="accordion">detail</a>
<%= f.submit "Submit",class: "btn btn-primary btn-xs" %>
<%= link_to "Delete", taskhank_path(task),class: "btn btn-primary btn-xs", method: :delete, data:{confirm: "確定刪除嗎?"} %>
</div>
</div>
<div id=<%= task.id %> class="panel-collapse collapse out">
<div class="row">
<div class="col-xs-5 col-xs-offset-1"><h5><strong><%= "Due day" %>
<%= task.due_date%></strong></h5></div>
<div class="col-xs-5 col-xs-offset-1"><%= f.label :note %>
<%= f.text_field :note%></div>
</div>
</div>

</div></div>

<% end %>


<% end %>

<% end %>
</div>

app/views/taskhanks/new.html.erb
  <%= form_for @task  do |f| %>
   <div class="container col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2">
   <h1 class="text-center">Creat your new task</h1>

   <hr >

   <div class="list">
    <div class="list-group-item well">
      <%= f.label :task %>
      <br />
      <%= f.text_field :task %>
    </div>
      <div class="list-group-item well">
      <%= f.label :due_date %>
       <br />
      <%= f.text_field :due_date %>
    </div>
      <div class="list-group-item well">
      <%= f.label :note %>
       <br />
      <%= f.text_field :note %>
    </div>

      <%= f.submit "Create", class: "col-xs-2 col-xs-offset-5 btn btn-primary" %>

    </div>
    </div>
  <% end %>

app/views/toms/index.html.erb
<h1>hello! Tom </h1>

app/views/users/index.html.erb
<div class="jumbotron jumbotron-success">
<div class="container">
  <h2>User請輸入Hank</h2>
  <h4>密碼請輸入1234</h4>
</div>
</div>




<%= form_for @user do |f| %>
<div class="container well col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1">
  <h2 class="text-center">Log in</h2>
  <br />

  <form action="">
    <div class="row">
    <div class="form-group col-xs-10 col-xs-offset-1">
      <%= f.label :name  %>
      <br>
      <%= f.text_field :name, class: "col-xs-12" , placeholder: "Enter your name" %>
    </div>
  </div>
  <div class="row">

    <div class="form-group col-xs-10 col-xs-offset-1">
      <%= f.label :password %>
      <br>
      <%= f.text_field :password,class: "col-xs-12", placeholder: "Enter the password" %>
    </div>
  </div>

    <br>
    <div class="form-group col-xs-10 col-xs-offset-1">
      <%= f.submit "Login", class: "btn btn-primary" %>
    </div>
  </form>
<% end %>